/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class at_sudo200_JConsole_JConsole */

#ifndef _Included_at_sudo200_JConsole_JConsole
#define _Included_at_sudo200_JConsole_JConsole
#ifdef __cplusplus
extern "C" {
#endif
#undef at_sudo200_JConsole_JConsole_BLACK
#define at_sudo200_JConsole_JConsole_BLACK 0L
#undef at_sudo200_JConsole_JConsole_RED
#define at_sudo200_JConsole_JConsole_RED 1L
#undef at_sudo200_JConsole_JConsole_GREEN
#define at_sudo200_JConsole_JConsole_GREEN 2L
#undef at_sudo200_JConsole_JConsole_YELLOW
#define at_sudo200_JConsole_JConsole_YELLOW 3L
#undef at_sudo200_JConsole_JConsole_BLUE
#define at_sudo200_JConsole_JConsole_BLUE 4L
#undef at_sudo200_JConsole_JConsole_MAGENTA
#define at_sudo200_JConsole_JConsole_MAGENTA 5L
#undef at_sudo200_JConsole_JConsole_CYAN
#define at_sudo200_JConsole_JConsole_CYAN 6L
#undef at_sudo200_JConsole_JConsole_WHITE
#define at_sudo200_JConsole_JConsole_WHITE 7L
#undef at_sudo200_JConsole_JConsole_GRAY
#define at_sudo200_JConsole_JConsole_GRAY 8L
#undef at_sudo200_JConsole_JConsole_H_RED
#define at_sudo200_JConsole_JConsole_H_RED 9L
#undef at_sudo200_JConsole_JConsole_H_GREEN
#define at_sudo200_JConsole_JConsole_H_GREEN 10L
#undef at_sudo200_JConsole_JConsole_H_YELLOW
#define at_sudo200_JConsole_JConsole_H_YELLOW 11L
#undef at_sudo200_JConsole_JConsole_H_BLUE
#define at_sudo200_JConsole_JConsole_H_BLUE 12L
#undef at_sudo200_JConsole_JConsole_H_MAGENTA
#define at_sudo200_JConsole_JConsole_H_MAGENTA 13L
#undef at_sudo200_JConsole_JConsole_H_CYAN
#define at_sudo200_JConsole_JConsole_H_CYAN 14L
#undef at_sudo200_JConsole_JConsole_H_WHITE
#define at_sudo200_JConsole_JConsole_H_WHITE 15L
#undef at_sudo200_JConsole_JConsole_C_INVISABLE
#define at_sudo200_JConsole_JConsole_C_INVISABLE 0L
#undef at_sudo200_JConsole_JConsole_C_SMALL
#define at_sudo200_JConsole_JConsole_C_SMALL 1L
#undef at_sudo200_JConsole_JConsole_C_MEDIUM
#define at_sudo200_JConsole_JConsole_C_MEDIUM 16L
#undef at_sudo200_JConsole_JConsole_C_LARGE
#define at_sudo200_JConsole_JConsole_C_LARGE 1024L
/*
 * Class:     at_sudo200_JConsole_JConsole
 * Method:    initConsole
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_at_sudo200_JConsole_JConsole_initConsole
  (JNIEnv *, jclass);

/*
 * Class:     at_sudo200_JConsole_JConsole
 * Method:    gotoxy
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_at_sudo200_JConsole_JConsole_gotoxy
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     at_sudo200_JConsole_JConsole
 * Method:    textcolor
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_at_sudo200_JConsole_JConsole_textcolor
  (JNIEnv *, jclass, jint);

/*
 * Class:     at_sudo200_JConsole_JConsole
 * Method:    textbackground
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_at_sudo200_JConsole_JConsole_textbackground
  (JNIEnv *, jclass, jint);

/*
 * Class:     at_sudo200_JConsole_JConsole
 * Method:    clrscr
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_at_sudo200_JConsole_JConsole_clrscr
  (JNIEnv *, jclass);

/*
 * Class:     at_sudo200_JConsole_JConsole
 * Method:    setCursorType
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_at_sudo200_JConsole_JConsole_setCursorType
  (JNIEnv *, jclass, jint);

/*
 * Class:     at_sudo200_JConsole_JConsole
 * Method:    delay
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_at_sudo200_JConsole_JConsole_delay
  (JNIEnv *, jclass, jint);

/*
 * Class:     at_sudo200_JConsole_JConsole
 * Method:    closeConsole
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_at_sudo200_JConsole_JConsole_closeConsole
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
